version: '3'

services:
  mysql-development:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hktv
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    security_opt:
      - seccomp:unconfined